# Global

variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - quality
  - tests

# Jobs templates

.install-deps-template: &install-deps
  before_script:
    - apt-get update
    - apt-get install -y aria2
    - pip install poetry
    - poetry config settings.virtualenvs.in-project true
    - poetry install -vv
    - poetry --version
    - aria2c --version

.quality-template: &quality
  <<: *install-deps
  image: python:3.6
  stage: quality


.test-template: &test
  <<: *install-deps
  stage: tests
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  script: make test
  artifacts:
    paths:
      - tests/logs
    when: on_failure
    expire_in: 1 week

# Quality jobs

check-bandit:
  <<: *quality
  script: make check-bandit

check-black:
  <<: *quality
  script: make check-black

check-flake8:
  <<: *quality
  script: make check-flake8

check-isort:
  <<: *quality
  script: make check-isort

check-safety:
  <<: *quality
  script: make check-safety

# Tests jobs

python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8

python3.6-windows:
  <<: *test
  image: python:3.6-windowsservercore
  allow_failure: true

python3.7-windows:
  <<: *test
  image: python:3.7-windowsservercore
  allow_failure: true

python3.8-windows:
  <<: *test
  image: python:3.8-windowsservercore
  allow_failure: true
