name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.6
      with:
        python-version: "3.8"

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: checks-cache

    - name: Resolving dependencies
      run: pdm lock

    - name: Install dependencies
      run: pdm install -G duty -G docs -G quality -G typing -G security

    - name: Check if the documentation builds correctly
      run: pdm run duty check-docs

    - name: Check the code quality
      run: pdm run duty check-quality

    - name: Check if the code is correctly typed
      run: pdm run duty check-types

    - name: Check for vulnerabilities in dependencies
      run: pdm run duty check-dependencies

  tests:

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11-dev"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
    - name: Install aria2 on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install aria2

    - name: Install aria2 on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install aria2

    - name: Install aria2 on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install aria2

    - name: Checkout
      uses: actions/checkout@v2    

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.6
      with:
        python-version: ${{ matrix.python-version }}
        version: 1.5.0b1

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: tests-cache-${{ runner.os }}-${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install -G tui -G duty -G tests

    - name: Run the test suite
      run: pdm run duty test
