name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.8"

    - name: Resolving dependencies
      run: pdm lock -v

    - name: Install dependencies
      run: pdm install -G duty -G docs -G quality -G typing -G security

    - name: Check if the documentation builds correctly
      run: pdm run duty check-docs

    - name: Check the code quality
      run: pdm run duty check-quality

    - name: Check if the code is correctly typed
      run: pdm run duty check-types

    - name: Check for vulnerabilities in dependencies
      run: pdm run duty check-dependencies

  tests:

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
    - name: Install aria2 on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install aria2

    - name: Install aria2 on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install aria2

    - name: Install aria2 on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install aria2

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        version: 1.5.0b1

    - name: Resolving dependencies
      run: pdm lock -v

    - name: Install dependencies
      run: pdm install --no-editable -G tui -G duty -G tests

    - name: Run the test suite
      run: pdm run duty test
